### ISSUE TITLE
python version

### ISSUE THREAD

**Issue by lucasrodes** [owid/data-utils-py#8]
Usually, a new python version is released every October. At the Data team, we plan to migrate to the new version every year around early April. 

This year, our plans are to transition to python 3.10 on 1st April.

Currently, the project's version is set to python >3.8. Would be nice to align on this, so we can use some of the new features from python 3.10.

**Comment by danyx23** [comment]
Can owid-catalog-py stay behind at 3.8? This is a library that is intended for public consumption and then it would be nice if you don't *have* to be running the very latest stable python version

**Comment by Marigold** [comment]
That's a good point, let's stick with 3.8+ then.

**Comment by lucasrodes** [comment]
@danyx23 That makes sense!

@Marigold I guess the plan is to use this library in owid-catalog-py too, right? Then let's stick to >3.8 for now here too.

**Comment by Marigold** [comment]
> I guess the plan is to use this library in owid-catalog-py too, right?

Yeah, I'm gonna add it there as soon as possible. Closing this for now.
